/**
 * Name:          TSDZ2 OSF Bike Head Unit
 * Author:        Gordon Moore
 * File:          manageState.js
 * Date:          13 August 2021
 * Description:   Code for managing the state
 * Licence        The MIT License https://opensource.org/licenses/MIT
 *
 * Version history
 * 0.0.1    13 August 2021     Initial version
 */
import React, { useState } from 'react'

export function setupInitialState() {
  console.log('and here')
  //#region set initial state
  const [motor_Voltage,                             setMotor_Voltage]                                 = useState(36)
  const [motor_Power_Max,                           setMotor_Power_Max]                               = useState(450)
  const [motor_Acceleration,                        setMotor_Acceleration]                            = useState(5)
  const [motor_Deceleration,                        setMotor_Deceleration]                            = useState(0)
  const [motor_Fast_Stop,                           setMotor_Fast_Stop]                               = useState(false)
  const [motor_Field_Weakening,                     setMotor_Field_Weakening]                         = useState(true)

  const [motor_Temperature_Enable,                  setMotor_Temperature_Enable]                      = useState('Throttle')
  const [motor_Temperature_Min_Limit,               setMotor_Temperature_Min_Limit]                   = useState(65)
  const [motor_Temperature_Max_Limit,               setMotor_Temperature_Max_Limit]                   = useState(85)

  const [torque_Assist_wo_pedal,                    setTorque_Assist_wo_pedal]                        = useState(false)
  const [torque_ADC_Threshold,                      setTorque_ADC_Threshold]                          = useState(10)
  const [torque_Coast_Brake,                        setTorque_Coast_Brake]                            = useState(false)
  const [torque_Coast_Brake_ADC,                    setTorque_Coast_Brake_ADC]                        = useState(10)
  const [torque_Calibration,                        setTorque_Calibration]                            = useState(true)
  const [torque_ADC_Step,                           setTorque_ADC_Step]                               = useState(30)
  const [torque_ADC_Offset,                         setTorque_ADC_Offset]                             = useState(148)
  const [torque_ADC_Max,                            setTorque_ADC_Max]                                = useState(306)
  const [torque_Weight_On_Pedal,                    setTorque_Weight_On_Pedal]                        = useState(20)
  const [torque_ADC_On_Weight,                      setTorque_ADC_On_Weight]                          = useState(263)
  const [torque_Default_Weight,                     setTorque_Default_Weight]                         = useState(false)
    
  const [battery_Max_current,                       setBattery_Max_current]                           = useState(11)
  const [battery_Low_Cut_Off,                       setBattery_Low_Cut_Off]                           = useState(39.0)
  const [battery_Resistance,                        setBattery_Resistance]                            = useState(200)
  const [battery_Voltage_Est,                       setBattery_Voltage_Est]                           = useState(0)
  const [battery_Resistance_Est,                    setBattery_Resistance_Est]                        = useState(0)
  const [battery_Power_Loss_Est,                    setBattery_Power_Loss_Est]                        = useState(0)
    
  const [soC_Text,                                  setSoC_Text]                                      = useState("SoC %")
  const [soC_Reset_At_Voltage,                      setSoC_Reset_At_Voltage]                          = useState(54.1)
  const [soC_Battery_Total_Wh,                      setSoC_Battery_Total_Wh]                          = useState(400.0)
  const [soC_Used,                                  setSoC_Used]                                      = useState(0.0)
  const [soC_Manual_Reset,                          setSoC_Manual_Reset]                              = useState(false)
    
  const [wheel_Max_Speed,                           setWheel_Max_Speed]                               = useState(70)
  const [wheel_Circumference,                       setWheel_Circumference]                           = useState(207)
    
  const [trip_A_Auto_Reset,                         setTrip_A_Auto_Reset]                             = useState(true)
  const [trip_A_Auto_Reset_Hours,                   setTrip_A_Auto_Reset_Hours]                       = useState(24)
  const [trip_B_Auto_Reset,                         setTrip_B_Auto_Reset]                             = useState(true)
  const [trip_B_Auto_Reset_Hours,                   setTrip_B_Auto_Reset_Hours]                       = useState(168) 
  const [trip_Reset_Trip_A,                         setTrip_Reset_Trip_A]                             = useState(false)
  const [trip_Reset_Trip_B,                         setTrip_Reset_Trip_B]                             = useState(false)
    
  const [number_Assist_Levels,                      setNumber_Assist_Levels]                          = useState(3)

  const [power_Assist_Level_1,                      setPower_Assist_Level_1]                          = useState(25)
  const [power_Assist_Level_2,                      setPower_Assist_Level_2]                          = useState(160)
  const [power_Assist_Level_3,                      setPower_Assist_Level_3]                          = useState(250)
  const [power_Assist_Level_4,                      setPower_Assist_Level_4]                          = useState(0)
  const [power_Assist_Level_5,                      setPower_Assist_Level_5]                          = useState(0)
  const [power_Assist_Level_6,                      setPower_Assist_Level_6]                          = useState(0)
  const [power_Assist_Level_7,                      setPower_Assist_Level_7]                          = useState(0)
  const [power_Assist_Level_8,                      setPower_Assist_Level_8]                          = useState(0)
  const [power_Assist_Level_9,                      setPower_Assist_Level_9]                          = useState(0)

  const [torque_Assist_Level_1,                     setTorque_Assist_Level_1]                         = useState(25)
  const [torque_Assist_Level_2,                     setTorque_Assist_Level_2]                         = useState(160)
  const [torque_Assist_Level_3,                     setTorque_Assist_Level_3]                         = useState(250)
  const [torque_Assist_Level_4,                     setTorque_Assist_Level_4]                         = useState(0)
  const [torque_Assist_Level_5,                     setTorque_Assist_Level_5]                         = useState(0)
  const [torque_Assist_Level_6,                     setTorque_Assist_Level_6]                         = useState(0)
  const [torque_Assist_Level_7,                     setTorque_Assist_Level_7]                         = useState(0)
  const [torque_Assist_Level_8,                     setTorque_Assist_Level_8]                         = useState(0)
  const [torque_Assist_Level_9,                     setTorque_Assist_Level_9]                         = useState(0)

  const [cadence_Assist_Level_1,                    setCadence_Assist_Level_1]                        = useState(100)
  const [cadence_Assist_Level_2,                    setCadence_Assist_Level_2]                        = useState(200)
  const [cadence_Assist_Level_3,                    setCadence_Assist_Level_3]                        = useState(250)
  const [cadence_Assist_Level_4,                    setCadence_Assist_Level_4]                        = useState(0)
  const [cadence_Assist_Level_5,                    setCadence_Assist_Level_5]                        = useState(0)
  const [cadence_Assist_Level_6,                    setCadence_Assist_Level_6]                        = useState(0)
  const [cadence_Assist_Level_7,                    setCadence_Assist_Level_7]                        = useState(0)
  const [cadence_Assist_Level_8,                    setCadence_Assist_Level_8]                        = useState(0)
  const [cadence_Assist_Level_9,                    setCadence_Assist_Level_9]                        = useState(0)

  const [eMTB_Assist_Level_1,                       setEMTB_Assist_Level_1]                           = useState(4)
  const [eMTB_Assist_Level_2,                       setEMTB_Assist_Level_2]                           = useState(13)
  const [eMTB_Assist_Level_3,                       setEMTB_Assist_Level_3]                           = useState(20)
  const [eMTB_Assist_Level_4,                       setEMTB_Assist_Level_4]                           = useState(0)
  const [eMTB_Assist_Level_5,                       setEMTB_Assist_Level_5]                           = useState(0)
  const [eMTB_Assist_Level_6,                       setEMTB_Assist_Level_6]                           = useState(0)
  const [eMTB_Assist_Level_7,                       setEMTB_Assist_Level_7]                           = useState(0)
  const [eMTB_Assist_Level_8,                       setEMTB_Assist_Level_8]                           = useState(0)
  const [eMTB_Assist_Level_9,                       setEMTB_Assist_Level_9]                           = useState(0)

  const [walk_Assist,                               setWalkAssist]                                    = useState(true)               
  const [walk_Assist_Cruise_Feature,                setWalk_Assist_Cruise_Feature]                    = useState(true)
  const [walk_Assist_Level_1,                       setWalk_Assist_Level_1]                           = useState(4)
  const [walk_Assist_Level_2,                       setWalk_Assist_Level_2]                           = useState(13)
  const [walk_Assist_Level_3,                       setWalk_Assist_Level_3]                           = useState(20)
  const [walk_Assist_Level_4,                       setWalk_Assist_Level_4]                           = useState(0)
  const [walk_Assist_Level_5,                       setWalk_Assist_Level_5]                           = useState(0)
  const [walk_Assist_Level_6,                       setWalk_Assist_Level_6]                           = useState(0)
  const [walk_Assist_Level_7,                       setWalk_Assist_Level_7]                           = useState(0)
  const [walk_Assist_Level_8,                       setWalk_Assist_Level_8]                           = useState(0)
  const [walk_Assist_Level_9,                       setWalk_Assist_Level_9]                           = useState(0)

  const [startup_Boost,                             setStartup_Boost]                                 = useState(true)
  const [startup_Boost_Torque_Factor,               setStartup_Boost_Torque_Factor]                   = useState(250)
  const [startup_Boost_Cadence_Step,                setStartup_Boost_Cadence_Step]                    = useState(25)

  const [street_Mode,                               setStreet_Mode]                                   = useState(true)
  const [street_Mode_Enable_At_Startup,             setStreet_Mode_Enable_At_Startup]                 = useState(false)
  const [street_Mode_Speed_Limit,                   setStreet_Mode_Speed_Limit]                       = useState(25)
  const [street_Mode_Motor_Power_Limit,             setStreet_Mode_Motor_Power_Limit]                 = useState(250)
  const [street_Mode_Throttle_Enable,               setStreet_Mode_Throttle_Enable]                   = useState(true)
  const [street_Mode_Cruise_Enable,                 setStreet_Mode_Cruise_Enable]                     = useState(false)
  const [street_Mode_Hotkey_Enable,                 setStreet_Mode_Hotkey_Enable]                     = useState(false)

  const [vars_Speed_Graph_Auto_Max_Min,             setVars_Speed_Graph_Auto_Max_Min]                 = useState(true)
  const [vars_Speed_Graph_Max,                      setVars_Speed_Graph_Max]                          = useState(0)
  const [vars_Speed_Graph_Min,                      setVars_Speed_Graph_Min]                          = useState(0)
  const [vars_Speed_Thresholds,                     setVars_Speed_Thresholds]                         = useState("Automatic")
  const [vars_Speed_Max_Threshold_Red,              setVars_Speed_Max_Threshold_Red]                  = useState(0)
  const [vars_Speed_Max_Threshold_Yellow,           setVars_Speed_Max_Threshold_Yellow]               = useState(0)

  const [vars_Trip_Dist_Graph_Auto_Max_Min,         setVars_Trip_Dist_Graph_Auto_Max_Min]             = useState(true)
  const [vars_Trip_Dist_Graph_Max,                  setVars_Trip_Dist_Graph_Max]                      = useState(0)
  const [vars_Trip_Dist_Graph_Min,                  setVars_Trip_Dist_Graph_Min]                      = useState(0)
  const [vars_Trip_Dist_Thresholds,                 setVars_Trip_Dist_Thresholds]                     = useState("Automatic")
  const [vars_Trip_Dist_Max_Threshold_Red,          setVars_Trip_Dist_Max_Threshold_Red]              = useState(0)
  const [vars_Trip_Dist_Max_Threshold_Yellow,       setVars_Trip_Dist_Max_Threshold_Yellow]           = useState(0)

  const [vars_Cadence_Graph_Auto_Max_Min,           setVars_Cadence_Graph_Auto_Max_Min]               = useState(true)
  const [vars_Cadence_Graph_Max,                    setVars_Cadence_Graph_Max]                        = useState(0)
  const [vars_Cadence_Graph_Min,                    setVars_Cadence_Graph_Min]                        = useState(0)
  const [vars_Cadence_Thresholds,                   setVars_Cadence_Thresholds]                       = useState("Automatic")
  const [vars_Cadence_Max_Threshold_Red,            setVars_Cadence_Max_Threshold_Red]                = useState(0)
  const [vars_Cadence_Max_Threshold_Yellow,         setVars_Cadence_Max_Threshold_Yellow]             = useState(0)

  const [vars_Human_Power_Graph_Auto_Max_Min,       setVars_Human_Power_Graph_Auto_Max_Min]           = useState(true)
  const [vars_Human_Power_Graph_Max,                setVars_Human_Power_Graph_Max]                    = useState(0)
  const [vars_Human_Power_Graph_Min,                setVars_Human_Power_Graph_Min]                    = useState(0)
  const [vars_Human_Power_Thresholds,               setVars_Human_Power_Thresholds]                   = useState("Automatic")
  const [vars_Human_Power_Max_Threshold_Red,        setVars_Human_Power_Max_Threshold_Red]            = useState(0)
  const [vars_Human_Power_Max_Threshold_Yellow,     setVars_Human_Power_Max_Threshold_Yellow]         = useState(0)


  const [vars_Motor_Power_Graph_Auto_Max_Min,       setVars_Motor_Power_Graph_Auto_Max_Min]           = useState(true)
  const [vars_Motor_Power_Graph_Max,                setVars_Motor_Power_Graph_Max]                    = useState(0)
  const [vars_Motor_Power_Graph_Min,                setVars_Motor_Power_Graph_Min]                    = useState(0)
  const [vars_Motor_Power_Thresholds,               setVars_Motor_Power_Thresholds]                   = useState("Automatic")
  const [vars_Motor_Power_Max_Threshold_Red,        setVars_Motor_Power_Max_Threshold_Red]            = useState(0)
  const [vars_Motor_Power_Max_Threshold_Yellow,     setVars_Motor_Power_Max_Threshold_Yellow]         = useState(0)

  const [vars_Watts_Km_Graph_Auto_Max_Min,          setVars_Watts_Km_Graph_Auto_Max_Min]              = useState(true)
  const [vars_Watts_Km_Graph_Max,                   setVars_Watts_Km_Graph_Max]                       = useState(0)
  const [vars_Watts_Km_Graph_Min,                   setVars_Watts_Km_Graph_Min]                       = useState(0)
  const [vars_Watts_Km_Thresholds,                  setVars_Watts_Km_Thresholds]                      = useState("Automatic")
  const [vars_Watts_Km_Max_Threshold_Red,           setVars_Watts_Km_Max_Threshold_Red]               = useState(0)
  const [vars_Watts_Km_Max_Threshold_Yellow,        setVars_Watts_Km_Max_Threshold_Yellow]            = useState(0)

  const [vars_Battery_Voltage_Graph_Auto_Max_Min,   setVars_Battery_Voltage_Graph_Auto_Max_Min]       = useState(true)
  const [vars_Battery_Voltage_Graph_Max,            setVars_Battery_Voltage_Graph_Max]                = useState(0)
  const [vars_Battery_Voltage_Graph_Min,            setVars_Battery_Voltage_Graph_Min]                = useState(0)
  const [vars_Battery_Voltage_Thresholds,           setVars_Battery_Voltage_Thresholds]               = useState("Automatic")
  const [vars_Battery_Voltage_Max_Threshold_Red,    setVars_Battery_Voltage_Max_Threshold_Red]        = useState(0)
  const [vars_Battery_Voltage_Max_Threshold_Yellow, setVars_Battery_Voltage_Max_Threshold_Yellow]     = useState(0)

  const [vars_Battery_Current_Graph_Auto_Max_Min,   setVars_Battery_Current_Graph_Auto_Max_Min]       = useState(true)
  const [vars_Battery_Current_Graph_Max,            setVars_Battery_Current_Graph_Max]                = useState(0)
  const [vars_Battery_Current_Graph_Min,            setVars_Battery_Current_Graph_Min]                = useState(0)
  const [vars_Battery_Current_Thresholds,           setVars_Battery_Current_Thresholds]               = useState("Automatic")
  const [vars_Battery_Current_Max_Threshold_Red,    setVars_Battery_Current_Max_Threshold_Red]        = useState(0)
  const [vars_Battery_Current_Max_Threshold_Yellow, setVars_Battery_Current_Max_Threshold_Yellow]     = useState(0)

  const [vars_Battery_SoC_Graph_Auto_Max_Min,       setVars_Battery_SoC_Graph_Auto_Max_Min]           = useState(true)
  const [vars_Battery_SoC_Graph_Max,                setVars_Battery_SoC_Graph_Max]                    = useState(0)
  const [vars_Battery_SoC_Graph_Min,                setVars_Battery_SoC_Graph_Min]                    = useState(0)
  const [vars_Battery_SoC_Thresholds,               setVars_Battery_SoC_Thresholds]                   = useState("Automatic")
  const [vars_Battery_SoC_Max_Threshold_Red,        setVars_Battery_SoC_Max_Threshold_Red]            = useState(0)
  const [vars_Battery_SoC_Max_Threshold_Yellow,     setVars_Battery_SoC_Max_Threshold_Yellow]         = useState(0)

  const [vars_Motor_Current_Graph_Auto_Max_Min,     setVars_Motor_Current_Graph_Auto_Max_Min]         = useState(true)
  const [vars_Motor_Current_Graph_Max,              setVars_Motor_Current_Graph_Max]                  = useState(0)
  const [vars_Motor_Current_Graph_Min,              setVars_Motor_Current_Graph_Min]                  = useState(0)
  const [vars_Motor_Current_Thresholds,             setVars_Motor_Current_Thresholds]                 = useState("Automatic")
  const [vars_Motor_Current_Max_Threshold_Red,      setVars_Motor_Current_Max_Threshold_Red]          = useState(0)
  const [vars_Motor_Current_Max_Threshold_Yellow,   setVars_Motor_Current_Max_Threshold_Yellow]       = useState(0)

  const [vars_Motor_Temp_Graph_Auto_Max_Min,        setVars_Motor_Temp_Graph_Auto_Max_Min]            = useState(true)
  const [vars_Motor_Temp_Graph_Max,                 setVars_Motor_Temp_Graph_Max]                     = useState(0)
  const [vars_Motor_Temp_Graph_Min,                 setVars_Motor_Temp_Graph_Min]                     = useState(0)
  const [vars_Motor_Temp_Thresholds,                setVars_Motor_Temp_Thresholds]                    = useState("Automatic")
  const [vars_Motor_Temp_Max_Threshold_Red,         setVars_Motor_Temp_Max_Threshold_Red]             = useState(0)
  const [vars_Motor_Temp_Max_Threshold_Yellow,      setVars_Motor_Temp_Max_Threshold_Yellow]          = useState(0)

  const [vars_Motor_Speed_Graph_Auto_Max_Min,       setVars_Motor_Speed_Graph_Auto_Max_Min]           = useState(true)
  const [vars_Motor_Speed_Graph_Max,                setVars_Motor_Speed_Graph_Max]                    = useState(0)
  const [vars_Motor_Speed_Graph_Min,                setVars_Motor_Speed_Graph_Min]                    = useState(0)
  const [vars_Motor_Speed_Thresholds,               setVars_Motor_Speed_Thresholds]                   = useState("Automatic")
  const [vars_Motor_Speed_Max_Threshold_Red,        setVars_Motor_Speed_Max_Threshold_Red]            = useState(0)
  const [vars_Motor_Speed_Max_Threshold_Yellow,     setVars_Motor_Speed_Max_Threshold_Yellow]         = useState(0)

  const [vars_Motor_PWM_Graph_Auto_Max_Min,         setVars_Motor_PWM_Graph_Auto_Max_Min]             = useState(true)
  const [vars_Motor_PWM_Graph_Max,                  setVars_Motor_PWM_Graph_Max]                      = useState(0)
  const [vars_Motor_PWM_Graph_Min,                  setVars_Motor_PWM_Graph_Min]                      = useState(0)
  const [vars_Motor_PWM_Thresholds,                 setVars_Motor_PWM_Thresholds]                     = useState("Automatic")
  const [vars_Motor_PWM_Max_Threshold_Red,          setVars_Motor_PWM_Max_Threshold_Red]              = useState(0)
  const [vars_Motor_PWM_Max_Threshold_Yellow,       setVars_Motor_PWM_Max_Threshold_Yellow]           = useState(0)

  const [vars_Motor_FOC_Graph_Auto_Max_Min,         setVars_Motor_FOC_Graph_Auto_Max_Min]             = useState(true)
  const [vars_Motor_FOC_Graph_Max,                  setVars_Motor_FOC_Graph_Max]                      = useState(0)
  const [vars_Motor_FOC_Graph_Min,                  setVars_Motor_FOC_Graph_Min]                      = useState(0)
  const [vars_Motor_FOC_Thresholds,                 setVars_Motor_FOC_Thresholds]                     = useState("Automatic")
  const [vars_Motor_FOC_Max_Threshold_Red,          setVars_Motor_FOC_Max_Threshold_Red]              = useState(0)
  const [vars_Motor_FOC_Max_Threshold_Yellow,       setVars_Motor_FOC_Max_Threshold_Yellow]           = useState(0)

  const [various_Lights_Configuration,              setVarious_Lights_Configuration]                  = useState(false)
  const [various_Assist_With_Error,                 setVarious_Assist_With_Error]                     = useState(false)
  const [various_Virtual_Throttle_Step,             setVarious_Virtual_Throttle_Step]                 = useState(10)
  const [various_Odometer,                          setVarious_Odometer]                              = useState(41.3)

  const [display_Clock_Hours,                       setDisplay_Clock_Hours]                           = useState(0)
  const [display_Clock_Minutes,                     setDisplay_Clock_Minutes]                         = useState(0)
  const [display_Brightness_On,                     setDisplay_Brightness_On]                         = useState(100)
  const [display_Brightness_Off,                    setDisplay_Brightness_Off]                        = useState(30)
  const [display_Auto_Power_Off,                    setDisplay_Auto_Power_Off]                        = useState(25)
  const [display_LCD_Type,                          setDisplay_LCD_Type]                              = useState('850C')
  const [display_860C_Shortcut_Key,                 setDisplay_860C_Shortcut_Key]                     = useState(false)
  const [display_Units,                             setDisplay_Units]                                 = useState(25)
  const [display_Reset_To_Defaults,                 setDisplay_Reset_To_Defaults]                     = useState(false)

  const [technical_ADC_Battery_Current,             setTechnical_ADC_Battery_Current]                 = useState(0)
  const [technical_ADC_Throttle_Sensor,             setTechnical_ADC_Throttle_Sensor]                 = useState(0)
  const [technical_Throttle_Sensor,                 setTechnical_Throttle_Sensor]                     = useState(0)
  const [technical_ADC_Torque_Sensor,               setTechnical_ADC_Torque_Sensor]                   = useState(148)
  const [technical_ADC_Torque_Delta,                setTechnical_ADC_Torque_Delta]                    = useState(0)
  const [technical_ADC_Torque_Boost,                setTechnical_ADC_Torque_Boost]                    = useState(0)
  const [technical_ADC_Torque_Step_Calc,            setTechnical_ADC_Torque_Step_Calc]                = useState(29)
  const [technical_Pedal_Cadence,                   setTechnical_Pedal_Cadence]                       = useState(0)
  const [technical_PWM_Duty_Cycle,                  setTechnical_PWM_Duty_Cycle]                      = useState(0)
  const [technical_Motor_Speed,                     setTechnical_Motor_Speed]                         = useState(0)
  const [technical_Motor_FOC,                       setTechnical_Motor_FOC]                           = useState(0)
  const [technical_Hall_Sensors,                    setTechnical_Hall_Sensors]                        = useState(0)
  //#endregion
  console.log('state loaded')
}
